### PR TITLE
Saving some memory for echo.

### PR DESCRIPTION
**Pull request by dseguy**

### CODE REVIEW

**Comment by nazar-pc** [comment]
Well, this is so-called micro-optimization, in fact almost all changed places are third-party components, other places are used in system during packages building, installation and when website disabling. All this means that there will be no benefit, even theoretical, when opening regular page.

**Comment by nicktacular** [comment]
See https://github.com/serbanghita/Mobile-Detect/pull/403

**Comment by nazar-pc** [comment]
@nicktacular, nice insight, but how did you found this PR?

**Comment by nicktacular** [comment]
It's on the public activity page.

**Pull request closed without merging**
